### ISSUE TITLE
  Better support for Golang

### ISSUE THREAD

**Issue by Ioridy** [fleps/cyber-purple-77-vscode-theme#1]
Hi,
﻿
I really like this purple theme for VSCode! Since I mainly use Golang for development, I'm hoping for improved support specifically tailored to Golang.
﻿
Thank you for considering this enhancement!

**Comment by fleps** [comment]
@Ioridy New version published on the marketplace.

I'm not super familiar with Go, but I noted it's a "typed" language, so I based the customizations from the structure I use on TypeScript, without any Go Language extension installed.

If you find anything weird or worth changing feel free to report here or open a new issue.

PS: when updating you might need to restart VScode and close/reopen files, or change the theme back and forth, sometimes VSCode it's weird with tokens updates on the theme already active (probably cache), and takes a minute to kick-in.

Cheers.
