### ISSUE TITLE
Set editor.selectionBackground to better visible colour

### ISSUE THREAD

**Issue by zrivkis** [fleps/cyber-purple-77-vscode-theme#3]
First of all, great theme! I really enjoy using it, so thank you for creating it. One recommendation that I have is to set `editor.selectionBackground` to something more visible as the current value is very hard to see. I've set mine to `#ffffff48` and find it much easier to work with. Thanks again for an awesome theme!

**Comment by fleps** [comment]
While the color is subject to personal taste and will vary from display to display, I increased the contrast a bit on the last update by setting it to `#2d1d3a`
